enum ROOM_WAYOUTS {
	TOP_CENTER = 1,
	TOP_RIGHT = 2,
	RIGHT_TOP = 3,
	RIGHT_CENTER = 4,
	RIGHT_BOTTOM = 5,
	BOTTOM_RIGHT = 6,
	BOTTOM_CENTER = -1,
	BOTTOM_LEFT = -2,
	LEFT_BOTTOM = -3,
	LEFT_CENTER = -4,
	LEFT_TOP = -5,
	TOP_LEFT = -6
}
